{...}:
{
  imports = [
    ./base_system.nix
    ./base_user.nix
    ./modern_boot.nix
    ./generic_desktop.nix
    ./generic_server.nix
    ./gnome.nix
    ./kde.nix
    ./hyprland.nix
    ./game_streaming_client.nix
    ./monitoring.nix
    ./media_server.nix
    ./flox.nix
    ./static_ip.nix
    ./authorized_keys.nix
  ];
}
