
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
    bootHelpers = pkgs.callPackage ../command_sets/boot.nix {};
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.xpadneo
  ];
  # Necessary for profiling
  boot.kernel.sysctl = {
    "perf_event_paranoid" = 1;
    "perf_event_mlock_kb" = 2048;
  };

  # Extra boot settings
  boot.loader.timeout = 0; # we have scripts for booting

  # Disable the wireless card
  networking.interfaces.wlp11s0.useDHCP = false;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nixpkgs.config.permittedInsecurePackages = [
    # I think these are from sonarr
    "dotnet-sdk-6.0.428"
    "aspnetcore-runtime-6.0.36"
  ];
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # GPU settings
  hardware.graphics.enable32Bit = true;
  services.xserver.videoDrivers = ["nvidia"];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.production;
  };
  hardware.graphics.extraPackages = with pkgs; [
    nvidia-vaapi-driver
    nvidia-system-monitor-qt
  ];

  programs.steam = {
    enable = true;
    extraCompatPackages = with pkgs; [
      pkgs.proton-ge-bin
    ];
  };

  # All this bullshit was to try to get my Xbox controller working.
  # One of these things makes it work, but don't ask me which one.
  hardware.xpadneo.enable = true;
  hardware.xone.enable = true;
  hardware.steam-hardware.enable = true;
  services.blueman.enable = true;
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings.General = {
      Privacy = "device";
      JustWorksRepairing = "always";
      FastConnectable = true;
    };
  };
  services.udev.packages = with pkgs; [
    game-devices-udev-rules
  ];

  # Sunshine game streaming server
  services.sunshine = {
    enable = true;
    openFirewall = true;
    capSysAdmin = true;
  };
  
  environment.systemPackages = with pkgs; [
    config.boot.kernelPackages.perf
    vscode
    linuxHeaders
    unstable.bpftrace
  ] ++ [
    bootHelpers
  ];

  environment.localBinInPath = true;

  # Otherwise it often fails during switch
  systemd.services.NetworkManager-wait-online.enable = false;
  
  # Custom modules
  media_server.enable = true;
  gnome.enable = true;
  generic_desktop.allowSleep = false;
  static_ip.enable = true;
  populate_authorized_keys.enable = true;
}
