# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, pkgs, modulesPath, inputs, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    (modulesPath + "/profiles/qemu-guest.nix")
    inputs.nixos-lima.nixosModules.lima
  ];

  # Lima stuff
  nix.settings.trusted-users = [ "@wheel" ];
  security = {
      sudo.wheelNeedsPassword = false;
  };
  services.openssh.enable = true;
  services.lima.enable = true;

  # system mounts
  # These settings match the image file generated by the NixOS Lima VM image generator
  boot.loader.grub = {
      device = "nodev";
      efiSupport = true;
      efiInstallAsRemovable = true;
  };
  fileSystems."/boot" = {
      device = lib.mkForce "/dev/vda1";  # /dev/disk/by-label/ESP
      fsType = "vfat";
  };
  fileSystems."/" = {
      device = "/dev/disk/by-label/nixos";
      autoResize = true;
      fsType = "ext4";
      options = [ "noatime" "nodiratime" "discard" ];
  };
  boot.kernelPackages = pkgs.linuxPackages_latest;

  networking.hostName = "nixos";
  environment.localBinInPath = true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  nix.settings.trusted-substituters = [
      "https://cache.flox.dev"
  ];
  nix.settings.trusted-public-keys = [
    "flox-cache-public-1:7F4OyH7ZCnFhcze3fJdfyXYLQw/aV7GEed86nQ7IsOs="
    # Public key for my private catalog
    "signing-key:a7ifhEZBmx+mP+z6cDgcBQzTZmtjHssCFkWWyI1dApg="
    # Meetrlyio catalog key
    "floxhub-meetrlyio-1:UVrkk/hwRCX8DEjrYF+2JjVP2ad3KUeya/1C5b3lsR8="
  ];
  nixpkgs.config.allowUnfree = true;
  nixpkgs.config.allowUnfreeRedistributable = true;
  nixpkgs.overlays = [
    (final: _prev: {
        unstable = import inputs.nixpkgs-unstable {
          inherit (final) system;
          config.allowUnfree = true;
        };
      })
  ];

  # Enables some commands to provide completions, etc for system-provided stuff
  environment.pathsToLink = [
    "/share/man"
  ];
 
  programs.fish.enable = true;
  generic_server.enable = true;

  populate_authorized_keys.enable = true;
  nix_community_cachix.enable = true;
}
