# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4902c1bc-7647-47ac-985c-4e6c25165e59";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/05CC-34CD";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/970b6715-c342-4171-a538-8f2660893e11"; }
    ];

  # networking.useDHCP = lib.mkDefault false;
  # networking.interfaces.enp86s0.useDHCP = lib.mkDefault true;
  networking.interfaces.enp86s0.ipv4.addresses = [
    {
      address = "10.0.0.166";
      prefixLength = 24;
    }
  ];
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable hardware acceleration of various things
  hardware.opengl.extraPackages = with pkgs; [
    intel-ocl
    intel-media-driver
    intel-vaapi-driver
  ];

  # Gaming stuff
  hardware.steam-hardware.enable = true;
  programs.steam.enable = true;

  # Pre-populate SSH keys from other machines
  users.users.zmitchell.openssh.authorizedKeys.keys = pkgs.lib.attrValues (
    pkgs.lib.filterAttrs (k: v: k != "smolboi") (import ../data/keys.nix));
  environment.systemPackages = with pkgs; [
    _1password-gui
  ];

  # Custom modules
  gnome.enable = true;

  # When switching back to Gnome you'll have to run this command:
  # dconf reset /org/gnome/desktop/interface/cursor-theme
  # kde.enable = true;

  game_streaming.enable = true;
}
